source 'https://rubygems.org'

gem 'cucumber'
gem 'watir'
gem 'page-object'
gem 'dotenv'
gem 'httparty'
gem 'json'
gem 'parallel_tests'
gem 'report_builder'
gem 'rspec-core'
gem 'rspec-expectations'
gem 'rubocop-rspec'
gem 'selenium-webdriver'
gem 'yard'
